theme: jekyll-theme-merlot

collections:
  players:
    output: true
    permalink: /:collection/:path
  npcs:
    output: true
    permalink: /:collection/:path
  locations:
    output: true
    permalink: /:collection/:path

    
